// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://skhlidhpgdaypzjctouo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNraGxpZGhwZ2RheXB6amN0b3VvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA3MjQ3NDcsImV4cCI6MjA3NjMwMDc0N30.6b5TyDpOW7PGsamYbnCtU6ZRPoz79mrpfzOSB4liV-I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);